// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdGrX2ylT80JKzVw0uZoRT_gekpfwnmR4',
    appId: '1:396849175008:web:28028f7943055b6bba7385',
    messagingSenderId: '396849175008',
    projectId: 'digital-farm-3bd30',
    authDomain: 'digital-farm-3bd30.firebaseapp.com',
    storageBucket: 'digital-farm-3bd30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIn822BeQnwgd9rQWbVRBLFLGykljZFzs',
    appId: '1:396849175008:android:f00645a456bf1359ba7385',
    messagingSenderId: '396849175008',
    projectId: 'digital-farm-3bd30',
    storageBucket: 'digital-farm-3bd30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6WRZwFm7KUhAUJJXvi7UPNxIgfT6NGlQ',
    appId: '1:396849175008:ios:19809561d68edeaeba7385',
    messagingSenderId: '396849175008',
    projectId: 'digital-farm-3bd30',
    storageBucket: 'digital-farm-3bd30.appspot.com',
    iosBundleId: 'com.example.digitalFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6WRZwFm7KUhAUJJXvi7UPNxIgfT6NGlQ',
    appId: '1:396849175008:ios:19809561d68edeaeba7385',
    messagingSenderId: '396849175008',
    projectId: 'digital-farm-3bd30',
    storageBucket: 'digital-farm-3bd30.appspot.com',
    iosBundleId: 'com.example.digitalFarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdGrX2ylT80JKzVw0uZoRT_gekpfwnmR4',
    appId: '1:396849175008:web:5c99104f66b2fc16ba7385',
    messagingSenderId: '396849175008',
    projectId: 'digital-farm-3bd30',
    authDomain: 'digital-farm-3bd30.firebaseapp.com',
    storageBucket: 'digital-farm-3bd30.appspot.com',
  );

}